workflows:
  flutter-android:
    name: Flutter Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - keystore
    scripts:
      - name: Set up Flutter
        script: |
          flutter channel stable
          flutter upgrade
          flutter --version
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Замените на ваш email
